# Generated by Django 4.1 on 2022-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_email', models.CharField(max_length=500)),
                ('product_number', models.IntegerField()),
                ('product_message', models.TextField()),
            ],
        ),
    ]
